using Microsoft.EntityFrameworkCore;
using QAP.Portal.API.Data;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddOpenApi();
builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
    });

builder.Services.AddDbContext<QapDbContext>(options =>
    options.UseOracle(builder.Configuration.GetConnectionString("OracleDb")));

var app = builder.Build();

// Automatic database tables creation on startup for Oracle DB
using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<QapDbContext>();
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
    try
    {
        using var command = context.Database.GetDbConnection().CreateCommand();
        context.Database.OpenConnection();

        // 1. QAP_LINE_GROUPS
        command.CommandText = @"
            DECLARE
                c NUMBER;
            BEGIN
                SELECT COUNT(*) INTO c FROM USER_TABLES WHERE TABLE_NAME = 'QAP_LINE_GROUPS';
                IF c = 0 THEN
                    EXECUTE IMMEDIATE 'CREATE TABLE QAP_LINE_GROUPS (
                        GROUP_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        QAP_DOCUMENT BLOB,
                        DRAWING_DOCUMENT BLOB,
                        QAP_NUMBER VARCHAR2(20),
                        STATUS VARCHAR2(1)
                    )';
                END IF;
            END;";
        command.ExecuteNonQuery();

        // 2. QAP_GROUP_ITEMS
        command.CommandText = @"
            DECLARE
                c NUMBER;
            BEGIN
                SELECT COUNT(*) INTO c FROM USER_TABLES WHERE TABLE_NAME = 'QAP_GROUP_ITEMS';
                IF c = 0 THEN
                    EXECUTE IMMEDIATE 'CREATE TABLE QAP_GROUP_ITEMS (
                        PO VARCHAR2(10),
                        LINE NUMBER(10),
                        ITEM_NO NUMBER(10),
                        GROUP_ID NUMBER(10) NOT NULL,
                        UPDATED_ON DATE,
                        UPDATED_BY VARCHAR2(50),
                        PRIMARY KEY (PO, LINE, ITEM_NO)
                    )';
                END IF;
            END;";
        command.ExecuteNonQuery();

        // 3. PO_DOCUMENTS
        command.CommandText = @"
            DECLARE
                c NUMBER;
            BEGIN
                SELECT COUNT(*) INTO c FROM USER_TABLES WHERE TABLE_NAME = 'PO_DOCUMENTS';
                IF c = 0 THEN
                    EXECUTE IMMEDIATE 'CREATE TABLE PO_DOCUMENTS (
                        PO VARCHAR2(10) PRIMARY KEY,
                        TECH_SPEC BLOB,
                        PO_COPY BLOB,
                        UPDATED_ON DATE,
                        UPDATED_BY VARCHAR2(50)
                    )';
                END IF;
            END;";
        command.ExecuteNonQuery();

        // 4. GROUP_ACTION_LOG
        command.CommandText = @"
            DECLARE
                c NUMBER;
            BEGIN
                SELECT COUNT(*) INTO c FROM USER_TABLES WHERE TABLE_NAME = 'GROUP_ACTION_LOG';
                IF c = 0 THEN
                    EXECUTE IMMEDIATE 'CREATE TABLE GROUP_ACTION_LOG (
                        SEQNO NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        GROUP_ID NUMBER(10) NOT NULL,
                        STAGE VARCHAR2(1),
                        ACTION_ON DATE,
                        ACTION_BY VARCHAR2(50),
                        REMARKS VARCHAR2(200)
                    )';
                END IF;
            END;";
        command.ExecuteNonQuery();

        logger.LogInformation("Database tables check/creation completed successfully.");

        // Auto-seed QAP_USERS if table is empty
        try
        {
            var userCount = await context.QapUsers.CountAsync();
            if (userCount == 0)
            {
                logger.LogInformation("Seeding default QAP_USERS...");
                context.QapUsers.Add(new QAP.Portal.API.Models.QapUser
                {
                    Email = "vardaansaxena096@gmail.com",
                    DisplayName = "Vardaan Saxena",
                    Role = "Initiator",
                    PasswordHash = BCrypt.Net.BCrypt.HashPassword("password123"),
                    IsActive = 1,
                    CreatedOn = DateTime.Now
                });
                context.QapUsers.Add(new QAP.Portal.API.Models.QapUser
                {
                    Email = "mansi@gail.co.in",
                    DisplayName = "Mansi",
                    Role = "Initiator",
                    PasswordHash = BCrypt.Net.BCrypt.HashPassword("password123"),
                    IsActive = 1,
                    CreatedOn = DateTime.Now
                });
                await context.SaveChangesAsync();
                logger.LogInformation("Default QAP_USERS seeded successfully.");
            }
        }
        catch (Exception seedEx)
        {
            logger.LogWarning(seedEx, "Failed to seed default QAP_USERS.");
        }
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "An error occurred while validating/creating database tables.");
    }
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseHttpsRedirection();

// Serve the frontend (wwwroot/index.html, css, js) from this same app.
app.UseDefaultFiles();
app.UseStaticFiles();

app.MapControllers();

// Any route that isn't an API call or a real static file falls back to
// index.html, so the frontend can handle its own in-page navigation.
app.MapFallbackToFile("index.html");

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast");

app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}